
const { Users } = require("../models").sequelize.models
const { checkUserPassword, generatePassword } = require("../utils/password");
const CustomError = require("../utils/CustomError");

class UserService {

    // creates a new user
    static async signUpUser(userInfo) {

        // checks if there is any other user with same email address.
        let userExists = await this.getUserByEmail(userInfo.email);
        if (userExists)
            throw new CustomError('User Already Exists', 409);

        // stores hashed password for user.
        let hashedPassword = await generatePassword(userInfo.password);

        // creates a new user.
        await Users.create({
            first_name: userInfo?.fname,
            last_name: userInfo?.lname,
            email: userInfo?.email,
            password: hashedPassword
        });
    }

    // authenticate user with credentials and gets user's info.
    static async loginUser(userInfo) {

        // find users with email address.
        let user = await this.getUserByEmail(userInfo.email);

        // check password is valid, if false send error
        if (!(await checkUserPassword(userInfo.password, user.password)))
            throw new CustomError('Email or password did not match', 200);

        const { password, createdAt, ...cleanUserData } = user;

        return cleanUserData;

    }

    // gets user's information by email.
    static async getUserByEmail(email) {
        // user generated by this function is used all over the server.
        const user = await Users.findOne({ where: { email: email }, raw: true });

        if (user)
            return user;
        throw new CustomError('Email or Password did not match');

    }
}

module.exports = UserService;