
const { Users } = require("../models").sequelize.models
const { checkUserPassword, generatePassword } = require("../utils/password");
const CustomError = require("../utils/CustomError");

class UserService {

    // creates a new user
    static async signUpUser(userInfo) {

        // checks if there is any other user with same email address.
        let userExists = await this.getUserByEmail(userInfo.email);
        if (userExists)
            throw new CustomError('User Already Exists', 409);

        // stores hashed password for user.
        let hashedPassword = await generatePassword(userInfo.password);

        // auto generates username for new user
        userInfo.username = '@' + userInfo.email.split('@')[0];
        console.log('userInfo.username :>> ', userInfo.username);
        // creates a new user.
        await Users.create({
            first_name: userInfo.fname,
            last_name: userInfo.lname,
            username: userInfo.username,
            email: userInfo.email,
            password: hashedPassword
        });
    }

    // authenticate user with credentials and gets user's info.
    static async loginUser(userInfo) {

        // find users with email address.
        let user = await this.getUserByEmail(userInfo.email);
        if (!user)
            throw new CustomError('Email or Password did not match', 401);

        // check password is valid, if false send error
        if (!(await checkUserPassword(userInfo.password, user.password)))
            throw new CustomError('Email or password did not match', 401);

        const { password, createdAt, ...cleanUserData } = user;

        return cleanUserData;

    }

    static async getUserById(userId) {
        const user = await Users.findByPk(userId, { raw: true });
        return user;
    }

    // gets user's information by email.
    static async getUserByEmail(email) {
        // user generated by this function is used all over the server.
        const user = await Users.findOne({ where: { email: email }, raw: true });
        return user;

    }
}

module.exports = UserService;